# Generated by Django 3.2.22 on 2023-10-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231020_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
