# Generated by Django 3.2.22 on 2024-01-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240101_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
